### ISSUE TITLE
Task exception was never retrieved

### ISSUE THREAD

**Issue by Magocrat** [warlockbrawl/war3observer#1]
Hi,

First of all, thank you for your tool.

During testing I often get this error:
`468767 Task exception was never retrieved
future: <Task finished coro=<Server.send_state() done, defined at war3observer\s
erver.py:36> exception=ConnectionClosed('WebSocket connection is closed: code =
1001 (going away), no reason')>
Traceback (most recent call last):
  File "war3observer\server.py", line 39, in send_state
  File "site-packages\websockets\protocol.py", line 462, in send
  File "site-packages\websockets\protocol.py", line 646, in ensure_open
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1
001 (going away), no reason`

Also, is there a possibility that war3observer works on NetEase replays?

**Comment by sides** [comment]
That's a non-error I neglected to handle properly, it shouldn't be displaying. It just signifies a client has exited (e.g. if you open the client in the browser and close the tab, the message should pop up).

I don't know about NetEase. I had hoped since it uses somewhat the same client, if mangled, the observer API would work on it too. But I guess they do something different if it's not working. I don't think I'll be able to look at this (I don't have NetEase installed), but maybe someone who knows the platform could.

**Comment by sides** [comment]
@Magocrat I've gotten rid of that annoying message now (pending release of 0.6.0). Netease support remains an open issue which I would love to include, especially on their replays, so I opened a separate one. #2
