### ISSUE TITLE
1.0

### ISSUE THREAD

**Issue by sides** [warlockbrawl/war3observer#10]
Warcraft III: Reforged is slated for a December release and judging by its current state I find it possible it will roll out with the observer API still enabled instead of new native observer tools. If this is the case, I would like to dedicate some time to fill in the gaps this tool has with a 1.0 release.

- [ ] Improve how the server handles sending out the game state to clients. (Server overhaul.)
- [ ] Make the server window friendlier: Add some relevant icon for the pyinstaller build, make it output more messages, so on.
- [ ] Upgrade to the latest mithril. Useful new features of new mithril include keyed components making lifecycle animations a cinch.
- [ ] Add support for HD. Most likely do this as a separate theme as well as extracting the new HD icons and assets. (Client overhaul.)
- [ ] Improve the look for team games. Make the resources for the whole team show in one box as well as possibly only showing heroes and their levels.
- [ ] Add FFA support. Do this as one scoreboard with information for all players.
- [ ] Add a Scoreboard view. Displays the names of two players/teams with their score next to them. Possible to override in-game names with their AKAs as well as displaying flags next to their names.
- [ ] Add a view for army compositions.
- [ ] Add a view for upgrades and tech in progress.
- [ ] Add hero revival timers.
- [ ] Add a Dashboard view. Has controls for hiding or displaying any of these components. Has controls for the scoreboard. Has controls to swap sides. (Can be embedded into OBS.)
- [ ] Improve client settings to accommodate new settings. Have the server remember settings for the session. Have settings be app-specific by default. Have `1v1-overview` include all components but hidden by default aside from resources/heroes. (A config file can enable them by default, or via the dashboard.)

I would also possibly like to create a new client so that this tool is no longer CLI only.

- [ ] Create an Electron app that includes a button to start the server as well as connecting to that server to build an interface to modify settings in the following manner (similar to the "Dashboard"):
- [ ] Add a theme picker to the app. It comes built-in with Default and Reforged themes, but the npm package will be revamped to be a theme builder (exports all components and a css file).
- [ ] Add tabs that represent different apps (`VersusApp`, `TeamVersusApp`, `FfaApp`, `ScoreboardApp`). Each tab controls the app's settings, including component visibility. All settings are done in a toggle-able manner, i.e. no manual user input, and will have the option to add a keyboard shortcut to cycle values.
- [ ] Add ability to save all these settings to disk.
- [ ] Create a ubiquitous html file that adapts to the current game mode on which app to display, i.e. only a single entry file needs to be added to OBS.

**Comment by KorKux1** [comment]
This has been a very interesting project, unfortunately I discovered it very recently. A few days before the reforged, it would be great if you gave support for the reforged.
3 days ago when I saw the project it caught my attention and I made a small view where it shows a lot of the information you want to put in new views: the heroes, training units, upgrades, etc. It has been very easy because of the way you built the API, certainly a great job.
Additionally to the todo list you have you could add to the dictionary that is sent from the war3structs the map information. In other words, the Map.py, this would be quite useful to put the map information. Since using the game.map_name found in the Observer.py returns the map patch.

**Comment by sides** [comment]
@KorKux1 Before dedicating time to it I'm going to see how Reforged releases. I've also edited the original post, I have some bigger ideas that I would like to spend some time on depending on the state of this January release.

Showing the map name can be done by reading the [map header](https://github.com/sides/war3structs/blob/master/war3structs/map.py#L30-L36) whenever a new path is encountered. Personally I don't understand the demand for it but it could be useful to add for other reasons.

**Comment by KorKux1** [comment]
@sides  Yes, I know that. What I mean is that you can add the option for the [dictionary](https://github.com/sides/war3observer/blob/52cf4cc5eea6c0cab61e003494978da2f41bcc23/war3observer/game.py#L146) to return the [MapHeader](https://github.com/sides/war3structs/blob/881223e99bf937309b3780dbe199d5ae6cd1f9a2/war3structs/map.py#L44).  I tried to make the server return this information to me without success.
Unfortunately the [map_name]() that the obs returns is not [what I expected](https://imgur.com/a/swyOhln)

That aside with respect to the names of the upgrades you mentioned in the [comments of the code](https://github.com/sides/war3structs/blob/881223e99bf937309b3780dbe199d5ae6cd1f9a2/war3structs/observer.py#L42) that had been removed due to the decoding but that this information could be opposed from some tables of the game. What tables did you mean?

**Comment by sides** [comment]
@KorKux1 I was just mentioning it as a note to self/anyone on how to eventually implement it. Currently no processing is done by the server on the API, it's sent as-is from `war3structs`. Adding map name would include an additional step by `game.py` which reads the map file on disk (`MapHeader.read_file(map_path)` or something like that), stores the result and replaces `map_name` in the dict with the real (English) name.

Upgrade names et al: If these are to be included an added step is needed similar to [`extract_icons.py`](https://github.com/sides/war3observer/blob/master/tools/extract_icons.py). A script will dig into an installation's game files, but instead of images, create a JSON file that matches IDs to names of game objects, such as upgrades and units. It would be an improved script that basically maps IDs to all information the overlay might need, such as a path to the icon and its English name.

Personally I'm against this because I have no idea how this will work on different locales: I think it is in the overlay's best interest to keep any text away. The script would be at the mercy of the locale of the client that the release build is created from (mine, in English). The map name will be at the mercy of whatever the map author put as the map name, but if the map includes different locale names (like all of the official maps) it will not be available on the overlay.

**Comment by sides** [comment]
Reforged is an unmitigated disaster and at this time I have no interest in spending my own time on this project anymore.
