### ISSUE TITLE
How memory scanning works?

### ISSUE THREAD

**Issue by thegrymek** [warlockbrawl/war3observer#13]
Refering to python mmap module:
* https://docs.python.org/3.0/library/mmap.html#mmap.mmap

To read wc3 memory you read from tag  "War3StatsObserverSharedMemory". How did you found this tag and what did you use to scan memory?

Thanks for this package and for library wc3-structs. It's very helpful and educational for me!

**Comment by sides** [comment]
I think the name of the file was in the patch notes or was part of a demo repository from a Blizzard developer or something like that. I'm not sure what you mean by scanning memory. To parse the format I examined the file in a hex editor from replays and was able to piece it together with some trial and error. There was no documentation on it at the time, but I think since Reforged the demo repository has been updated with the full spec.

**Comment by thegrymek** [comment]
> I think since Reforged the demo repository has been updated with the full spec.

Could you provide link to demo repository?

**Comment by sides** [comment]
https://github.com/TinkerWorX/Blizzard.Net.Warcraft3

**Comment by thegrymek** [comment]
Thank so much!
I found this name:
* [link where is "War3StatsObserverSharedMemory" ](https://github.com/TinkerWorX/Blizzard.Net.Warcraft3/blob/master/Blizzard.Net.Warcraft3/Statistics/ObserverData.cs
)

I'm clossing the issue. Thanks you so much for support and help again!

**Comment by sides** [comment]
Np, thanks for the interest in the project. Just to add, if you were having issues opening the file or the file coming up blank with mmap, ever since Reforged the observer API doesn't update automatically unless you first write a refresh rate to it (defaults as 0). You can see me adding the write in [this commit](https://github.com/sides/war3observer/commit/b236a9b6a2d69a526f5270c39feafb030d92d79b) (in `game.py`). This caused me some headache when trying to examine the file post-Reforged.
