### ISSUE TITLE
INFO: observer 0.8.2

### ISSUE THREAD

**Issue by OzZy02100** [warlockbrawl/war3observer#3]
Hello, 

After set all like you said, 
I have this message : INFO: observer **0.8.2

 but not the overlay

What can i do?? 

Thanks you in Advance !

**Comment by OzZy02100** [comment]
Now i have this more

ERROR: An error occurred while updating the game state
Traceback (most recent call last):
  File "war3observer\server.py", line 44, in send_state_to_client
  File "war3observer\game.py", line 140, in update
  File "war3observer\game.py", line 112, in _find_players
Exception: Attempted to find 2 players but found only 0

**Comment by OzZy02100** [comment]
THis seems to only work into watching replay...

even if i change the html file to put 1v1 overview and not replay ??? Why Thx you in advance

**Comment by sides** [comment]
Here is a common troubleshooting technique:

1. Fully close both `war3observer.exe` and Warcraft III
2. Start Warcraft III, and wait for it to be fully started, showing the menu screen
3. Start `war3observer.exe`
4. Enter a game (replay or live) and then refresh the view (`1v1-overview.html` or otherwise in your browser or refresh cache in OBS)

If that's not working, can you tell me the details of the game where you encounter issues? Such as: are you testing with computers, what map are you playing on, is it on Netease or bnet?

In regards to this:

> ERROR: An error occurred while updating the game state
> Traceback (most recent call last):
> File "war3observer\server.py", line 44, in send_state_to_client
> File "war3observer\game.py", line 140, in update
> File "war3observer\game.py", line 112, in _find_players
> Exception: Attempted to find 2 players but found only 

Have you made sure you are an observer, and not a player?

**Comment by OzZy02100** [comment]
you Mean, this dont work during ladder 1v1 ???

 We have to be observer ? so only for custom game ?

Cause my hope was to have only my part with heroes and stuff , not opponent part of course during stream

**Comment by sides** [comment]
It's only for custom games, yes, i.e. for casting games. If you are looking for something for your stream, there is this tool for opponent stats: https://github.com/dethredic/WC3StreamerOverlay
Though it will not display your hero information.
