### ISSUE TITLE
After following setup instructions, overlay still not appearing in OBS. Assistance needed

### ISSUE THREAD

**Issue by gabcinder2004** [warlockbrawl/war3observer#5]
Hey there, I am working with a warcraft 3 streamer to get this overlay setup and for some reason it is not working. I was able to set it up on my OBS, but for some reason his overlay will not appear on his stream. Would you be willing to hop on discord with us and help us troubleshoot?

**Comment by sides** [comment]
I would recommend following the steps here: https://github.com/warlockbrawl/war3observer/issues/3#issuecomment-483194630

The readme is a bit unclear with its instructions because what can cause the overlay to stop functioning is if war3observer.exe is started before wc3. Then, sometimes, the only way to get it working again is to **fully close both** and then start wc3 (or restarting your computer).

If this is not the problem for them then you can dm me on discord, hildur#4405

**Comment by cammed** [comment]
Hello!
There is a question. Is it possible to change the program to work with old patches, for example 1.18?

**Comment by sides** [comment]
@cammed No. The observer API was added in 1.30.2 or something like that and this will not work with any patch prior.
